### ISSUE TITLE
Integration fails to start after updating to 1.4.0

### ISSUE THREAD

**Issue by othi** [snazzybean/roommind#85]
### RoomMind version

1.4.0

### Home Assistant version

2026.3.1

### Installation method

HACS

### Description

After updating to 1.4.0 (and HA 2026.3.1 at the same time), the integration no longer starts.

### Steps to reproduce

Update to 1.4.0, reboot HA.

### Relevant log output

```text
Logger: homeassistant.config_entries
Source: config_entries.py:769
First occurred: 14:57:02 (2 occurrences)
Last logged: 17:41:49

Error setting up entry RoomMind for roommind
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 769, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roommind/__init__.py", line 55, in async_setup_entry
    coordinator.cleanup_orphaned_entities()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/roommind/coordinator.py", line 1024, in cleanup_orphaned_entities
    if not uid or not uid.startswith(f"{DOMAIN}_"):
                      ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'startswith'
```

**Comment by snazzybean** [comment]
Should work now in [v1.4.1](https://github.com/snazzybean/roommind/releases/tag/v1.4.1).

**Comment by othi** [comment]
Can confirm, it's running!

Thanks
